name: Build Docker Images for PHP 8.2 with Apache
on:
  workflow_dispatch:
    branches:
      - master
    paths:
      - "8/8.2/Dockerfile.apache"
      - "8/8.2/Dockerfile.apache.dev"
  push:
    branches:
      - "master"
    paths:
      - "8/8.2/Dockerfile.apache"
      - "8/8.2/Dockerfile.apache.dev"
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      ## Login to all 3 registries: DockerHub, GitHub Actions Container Registry, and Quay.io ##
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to the GitHub Actions Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Login to the Quay.io Container Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      ## Build and push the Docker image ##
      - name: Build and push the Apache Production Image
        uses: docker/build-push-action@v5
        with:
          context: 8/8.2
          file: 8/8.2/Dockerfile.apache
          build-args: |
            PHP_VERSION=8.2
          push: true
          tags: |
            islamicnetwork/php:8.2-apache
            ghcr.io/islamic-network/php:8.2-apache
            quay.io/islamic-network/php:8.2-apache
      - name: Build and push the Apache Development Image
        uses: docker/build-push-action@v5
        with:
          context: 8/8.2
          file: 8/8.2/Dockerfile.apache.dev
          build-args: |
            PHP_VERSION=8.2
          push: true
          tags: |
            islamicnetwork/php:8.2-apache-dev
            ghcr.io/islamic-network/php:8.2-apache-dev
            quay.io/islamic-network/php:8.2-apache-dev
