name: Build Docker Images for PHP 8.4 (CLI)
on:
  workflow_dispatch:
    branches:
      - master
    paths:
      - "8/8.4/Dockerfile.cli"
  push:
    branches:
      - "master"
    paths:
      - "8/8.4/Dockerfile.cli"
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      ## Login to all 3 registries: DockerHub, GitHub Actions Container Registry, and Quay.io ##
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to the GitHub Actions Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Login to the Bahriya Container Registry
        uses: docker/login-action@v3
        with:
          registry: bcr.ax
          username: ${{ secrets.BCR_USERNAME }}
          password: ${{ secrets.BCR_PASSWORD }}
      - name: Login to the Quay.io Container Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      ## Build and push the Docker image ##
      - name: Build and push the CLI Image
        uses: docker/build-push-action@v5
        with:
          context: 8/8.3
          platforms: linux/amd64,linux/arm64
          file: 8/8.3/Dockerfile.cli
          build-args: |
            PHP_VERSION=8.4
          push: true
          tags: |
            bcr.ax/library/php:8.3-cli
            islamicnetwork/php:8.3-cli
            ghcr.io/islamic-network/php:8.3-cli
            quay.io/islamic-network/php:8.3-cli
